server:
  port: 8090

integration:
  auth0:
    url: https://<domain>
    client_id: <client_id>
    client_secret: <client_secret>
  keycloak:
    realm: quickstart
    url: http://localhost:8180/realms/${realm}/protocol/openid-connect
    client_id: webapp-client
    client_secret:

clients:
  - name: demo-client-1
    authorize-url: ${integration.auth0.url}/authorize
    access-token-url: ${integration.auth0.url}/oauth/token
    client-id: ${integration.auth0.client_id}
    client-secret: ${integration.auth0.client_secret}
    scope: "openid email profile offline_access"
    redirect_uri: http://localhost:8090/callback
    audience: http://localhost:8090
  - name: demo-client-2
    authorize-url: ${integration.keycloak.url}/auth
    access-token-url: ${integration.keycloak.url}/token
    client-id: ${integration.keycloak.client_id}
    client_secret: ${integration.keycloak.client_secret}
    scope: "openid email profile"
    redirect_uri: http://localhost:3000