server:
  port: 8095

logging:
  level:
    root: INFO
    org.example: DEBUG
    org.springframework.security: trace

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: https://dev-hhahrzni3t6tv1sl.eu.auth0.com/
          jws-algorithms: RS256
          #jwk-set-uri: https://dev-hhahrzni3t6tv1sl.eu.auth0.com/.well-known/jwks.json
          #audiences: ["http://localhost:8090"]  # needed only for Auth0
          issuer-uri: http://localhost:8180/realms/quickstart
          jwk-set-uri: http://localhost:8180/realms/quickstart/protocol/openid-connect/certs

security:
  provider: KEYCLOAK
  client-id: webapp-client #needed only for Keycloak