server:
  port: 8095

logging:
  level:
    root: INFO
    org.example: DEBUG
    org.springframework.security: trace

security:
  tenants:
    - issuer: http://localhost:8180/realms/quickstart
      jws-algorithm: RS256
      jwk-set-uri: http://localhost:8180/realms/quickstart/protocol/openid-connect/certs
    - issuer: http://localhost:8180/realms/operations
      jws-algorithm: RS256
      jwk-set-uri: http://localhost:8180/realms/operations/protocol/openid-connect/certs