server:
  port: 8095

logging:
  level:
    root: INFO
    org.example: DEBUG
    org.springframework.security: trace

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS256
          #issuer-uri: http://localhost:8180/realms/quickstart
          #jwk-set-uri: http://localhost:8180/realms/quickstart/protocol/openid-connect/certs

security:
  issuers:
    - http://localhost:8180/realms/quickstart
    - http://localhost:8180/realms/operations